#pragma once

/**
 * @brief Custom assertion function for detailed failure reporting.
 *
 * If the 'expected' condition is false, this function logs an error message including
 * the file name, line number, the expected condition as a string, and an optional message.
 * If 'expected' is true, the function returns without any action.
 *
 * @param expected Boolean result of the condition being checked.
 * @param expected_str String representation of the expected condition (usually generated by macro).
 * @param file Source file name where the assertion failed.
 * @param line Line number in the source code where the assertion failed.
 * @param message Optional additional message to provide more context (default is nullptr).
 */
void __assert(
    bool expected,
    const char* expected_str,
    const char* file,
    int line,
    const char* message = nullptr
);

/**
 * @brief Assertion macro with logging and source location.
 *
 * Evaluates 'Expected'; if it is false, calls __assert with the boolean value,
 * the stringified condition, file name, line number, and an optional message.
 *
 * Usage example:
 *   VKM_ASSERT(ptr != nullptr, "Pointer should not be null");
 *
 * @param Expected Expression to check.
 * @param ... Optional message or argument.
 */
#ifdef NDEBUG
// Release build: disable assertion checking for performance
 #define VKM_ASSERT(Expected, ...) true
#else
// Debug build: enable assertion checking
#define VKM_ASSERT(Expected, ...)                                   \
    __assert(Expected, #Expected, __FILE__, __LINE__, ##__VA_ARGS__)
#endif
